directories:
  output: release
  buildResources: resources
productName: Bingo
appId: org.Bingo
dmg:
  contents:
    - x: 130
      'y': 220
    - x: 410
      'y': 220
      type: link
      path: /Applications
win:
  target:
    - nsis
    - msi
linux:
  target:
    - deb
    - rpm
    - snap
    - AppImage
  category: Development
files: []
electronVersion: 13.1.7
